services:
  api:
    container_name: api_container
    build: ./backend/
    ports:
      - "3001:3001"
    networks:
      - app_network
  nginx:
    build: ./frontend/
    container_name: nginx_container
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
networks:
  app_network:
    driver: bridge