services:
  mongo_db: 
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes: 
      - ./backend/mongo_db:/data/db
    ports:  
      - 27017:27017
    networks:
      - app_network
  api:
    container_name: api_container
    build: ./backend/
    ports:
      - "3001:3001"
    environment:
      DB_URI: "mongodb://mongo_db:27017/test"
      PORT: 3001
    depends_on:
      - mongo_db
    networks:
      - app_network
  nginx:
    build: ./frontend/
    container_name: nginx_container
    ports:
      - "80:80"
    networks:
      - app_network
    volumes:
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
networks:
  app_network:
    driver: bridge